# Generated by Django 5.1.5 on 2025-01-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_place_delete_tbl_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_place',
        ),
    ]
