# Generated by Django 5.1.5 on 2025-02-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motherboard_name', models.CharField(max_length=30)),
                ('motherboard_details', models.CharField(max_length=30)),
            ],
        ),
    ]
