# Generated by Django 5.1.5 on 2025-02-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_motherboard',
        ),
    ]
