# Generated by Django 5.1.5 on 2025-02-14 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_delete_tbl_motherboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motherboard_name', models.CharField(max_length=30)),
                ('motherboard_details', models.CharField(max_length=30)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_brand')),
            ],
        ),
    ]
