# Generated by Django 5.1.5 on 2025-02-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_motherboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_motherboard',
            name='brand',
        ),
        migrations.DeleteModel(
            name='tbl_brand',
        ),
        migrations.DeleteModel(
            name='tbl_motherboard',
        ),
    ]
