# Generated by Django 5.1.5 on 2025-02-15 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_tbl_brand_tbl_motherboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_motherboard',
            name='motherboard_photo',
            field=models.FileField(upload_to='Assets/Admin/Photo/'),
        ),
        migrations.CreateModel(
            name='tbl_processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_name', models.CharField(max_length=30)),
                ('processor_details', models.CharField(max_length=30)),
                ('processor_price', models.CharField(max_length=30)),
                ('processor_photo', models.FileField(upload_to='Assets/Admin/Photo/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_brand')),
            ],
        ),
    ]
