# Generated by Django 5.1.5 on 2025-02-15 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_alter_tbl_motherboard_motherboard_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_name', models.CharField(max_length=30)),
                ('ram_details', models.CharField(max_length=30)),
                ('ram_price', models.CharField(max_length=30)),
                ('ram_photo', models.FileField(upload_to='Assets/Admin/Photo/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_brand')),
            ],
        ),
    ]
