# Generated by Django 5.1.5 on 2025-02-15 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_tbl_ram'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_graphicscard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphicscard_name', models.CharField(max_length=30)),
                ('graphicscard_details', models.CharField(max_length=30)),
                ('graphicscard_price', models.CharField(max_length=30)),
                ('graphicscard_photo', models.FileField(upload_to='Assets/Admin/Photo/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_brand')),
            ],
        ),
    ]
