# Generated by Django 5.1.5 on 2025-02-15 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_tbl_graphicscard'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rom_name', models.CharField(max_length=30)),
                ('rom_details', models.CharField(max_length=30)),
                ('rom_price', models.CharField(max_length=30)),
                ('rom_photo', models.FileField(upload_to='Assets/Admin/Photo/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_brand')),
            ],
        ),
    ]
