# Generated by Django 5.1.5 on 2025-02-25 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_tbl_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_casecooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casecooler_name', models.CharField(max_length=30)),
                ('casecooler_details', models.CharField(max_length=30)),
                ('casecooler_price', models.CharField(max_length=30)),
                ('casecooler_photo', models.FileField(upload_to='Assets/Admin/Photo/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_brand')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_cpucooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpucooler_name', models.CharField(max_length=30)),
                ('cpucooler_details', models.CharField(max_length=30)),
                ('cpucooler_price', models.CharField(max_length=30)),
                ('cpucooler_photo', models.FileField(upload_to='Assets/Admin/Photo/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_brand')),
            ],
        ),
    ]
