# Generated by Django 5.1.5 on 2025-02-27 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_tbl_casecooler_tbl_cpucooler'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_powersupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powersupply_name', models.CharField(max_length=30)),
                ('powersupply_details', models.CharField(max_length=30)),
                ('powersupply_price', models.CharField(max_length=30)),
                ('powersupply_photo', models.FileField(upload_to='Assets/Admin/Photo/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_brand')),
            ],
        ),
    ]
