# Generated by Django 5.1.5 on 2025-02-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0022_tbl_powersupply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_product',
        ),
    ]
