# Generated by Django 5.1.5 on 2025-02-27 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0023_delete_tbl_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_details', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=30)),
                ('product_photo', models.FileField(upload_to='Assets/Admin/Photo/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_brand')),
            ],
        ),
    ]
