# Generated by Django 5.1.5 on 2025-02-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_product_amount_tbl_booking_booking_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_customise',
            name='custome_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
