# Generated by Django 5.1.5 on 2025-03-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_tbl_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_customise',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='tbl_customise',
            name='rom',
        ),
    ]
