# Generated by Django 5.1.5 on 2025-03-04 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0025_tbl_stock'),
        ('User', '0009_remove_tbl_customise_ram_remove_tbl_customise_rom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_customise',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_case'),
        ),
        migrations.AlterField(
            model_name='tbl_customise',
            name='casecooler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_casecooler'),
        ),
        migrations.AlterField(
            model_name='tbl_customise',
            name='cpucooler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_cpucooler'),
        ),
        migrations.AlterField(
            model_name='tbl_customise',
            name='custome_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbl_customise',
            name='graphicscard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_graphicscard'),
        ),
        migrations.AlterField(
            model_name='tbl_customise',
            name='motherboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_motherboard'),
        ),
        migrations.AlterField(
            model_name='tbl_customise',
            name='powersupply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_powersupply'),
        ),
        migrations.AlterField(
            model_name='tbl_customise',
            name='processor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_processor'),
        ),
    ]
