# Generated by Django 5.1.5 on 2025-03-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_tbl_customise_case_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_customise',
        ),
    ]
