# Generated by Django 5.1.5 on 2025-03-04 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0025_tbl_stock'),
        ('Guest', '0001_initial'),
        ('User', '0011_delete_tbl_customise'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_customise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custome_date', models.DateField(auto_now_add=True)),
                ('custome_amount', models.IntegerField(null=True)),
                ('custome_status', models.IntegerField(default=0)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_case')),
                ('casecooler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_casecooler')),
                ('cpucooler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_cpucooler')),
                ('graphicscard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_graphicscard')),
                ('motherboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_motherboard')),
                ('powersupply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_powersupply')),
                ('processor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_processor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
