# Generated by Django 5.1.5 on 2025-03-06 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0025_tbl_stock'),
        ('User', '0012_tbl_customise'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ramhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_customise')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ram')),
            ],
        ),
    ]
