# Generated by Django 5.1.5 on 2025-03-06 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0025_tbl_stock'),
        ('User', '0013_tbl_ramhead'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_romhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_customise')),
                ('rom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_rom')),
            ],
        ),
    ]
