# Generated by Django 5.2 on 2025-04-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_tbl_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_chat',
            name='user_to',
        ),
    ]
