# Generated by Django 5.2 on 2025-04-15 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
        ('User', '0016_remove_tbl_chat_user_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_chat',
            name='user_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Guest.tbl_user'),
        ),
    ]
